version: "2"
services:
  web:
    container_name: laravel_web
    image: nginx:alpine
    links:
      - php
    ports:
      - "9090:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
      - php
  php:
    container_name: laravel_php
    image: goeroeku/php-fpm-alpine:7.3.1
    links:
      - db
    volumes:
      - ./htdocs:/var/www/html
  db:
    container_name: laravel_db
    image: jbergstroem/mariadb-alpine
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=homestead
      - MYSQL_USER=homestead
      - MYSQL_PASSWORD=secret
    volumes:
      - ./mysql:/var/lib/mysql
